### PR TITLE
LRAC-8146 Adding TotalNumberOfIndividualsIsShown Test

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-8146

### CODE REVIEW

**Comment by christianstokes** [comment]
@alexcandidos is the point of this test to check the total plan amount (100,000) or is it to check that it shows the total number of current individuals (200)?

See:
total_usage

**Comment by alexcandidos** [comment]
Hi @christianstokes, in this test we are validating the total plan amount (100,000), the same for https://github.com/alexcandidos/liferay-portal/pull/494, there we are validating the limit amount of individuals.

The increase of these numbers (individuals and page views) are being covered by the tests implemented on https://github.com/alexcandidos/liferay-portal/pull/490 and https://github.com/alexcandidos/liferay-portal/pull/493

--

Hey @AfonsoHSantos , could you please update this test case name for `PlanLimitNumberOfIndividualsIsShown` and on #494, for `PlanLimitNumberOfPageViewsIsShown`, so it will be more clear and linked to the test purpose.

**Comment by alexcandidos** [comment]
Aside that, the code looks good to me!

**Comment by AfonsoHSantos** [comment]
Hi @alexcandidos, I made the changes you asked for!

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
