### PR TITLE
AC Stub Test - LRAC-8442, LRAC-8447, LRAC-8450, LRAC-8452, LRAC-8455, LRAC-8457 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-8442
https://issues.liferay.com/browse/LRAC-8447
https://issues.liferay.com/browse/LRAC-8450
https://issues.liferay.com/browse/LRAC-8452
https://issues.liferay.com/browse/LRAC-8455
https://issues.liferay.com/browse/LRAC-8457

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
