### PR TITLE
LPS-126301

### PR DESCRIPTION
**Pull request by brunoquei2105**

### CODE REVIEW

**Comment by alexcandidos** [comment]
Hey @brunoquei2105 , your test need the DataEngineBuilder.path that is missing in this PR.
Please resend.

**Comment by brunoquei2105** [comment]
Ok

**Comment by brunoquei2105** [comment]
Eita...entao vão voltar todos...pq o DataEngineBuilder.path nao ta na master.

**Comment by alexcandidos** [comment]
Exactly @brunoquei2105, your PR should contain all the needed files/dependencies to run your test.

**Pull request closed without merging**
