### PR TITLE
LRQA-62451 Creating data-engine test suite to run all DDL scripts

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
It will run the following functional tests:
```
RUN_TEST_CASE_METHOD_GROUP_0=0_0 0_1 0_2 0_3 0_4 0_5 0_6 0_7 0_8 0_9 0_10 0_11 0_12 0_13 0_14
RUN_TEST_CASE_METHOD_GROUP_0_0=LocalFile.DDLSalesdemo#Demo1
RUN_TEST_CASE_METHOD_GROUP_0_1=LocalFile.DynamicdatalistsUpgrade#AddDataDefinitionAfterUpgrade621021
RUN_TEST_CASE_METHOD_GROUP_0_2=LocalFile.DDMStructureWithTranslations#ViewFieldInputWhenSwitchingTranslations
RUN_TEST_CASE_METHOD_GROUP_0_3=LocalFile.DDMStructureWithNestedTextField#ViewFieldTranslations
RUN_TEST_CASE_METHOD_GROUP_0_4=LocalFile.DDMTemplate#ViewCacheableCheckbox
RUN_TEST_CASE_METHOD_GROUP_0_5=LocalFile.DDMStructureWithImageField#ViewFieldTranslations
RUN_TEST_CASE_METHOD_GROUP_0_6=LocalFile.DDMStructuresStaging#AddWebContentTemplateWithSmallImage
RUN_TEST_CASE_METHOD_GROUP_0_7=LocalFile.DDMStructuresStaging#CreateWebContentStructureAndTemplate
RUN_TEST_CASE_METHOD_GROUP_0_8=LocalFile.PGDynamicdatalists#AddFormTemplate
RUN_TEST_CASE_METHOD_GROUP_0_9=LocalFile.PGDynamicdatalists#AddList
RUN_TEST_CASE_METHOD_GROUP_0_10=LocalFile.PGDynamicdatalists#AddListRecord
RUN_TEST_CASE_METHOD_GROUP_0_11=LocalFile.PGDynamicdatalists#AddListWithDocumentsAndMediaField
RUN_TEST_CASE_METHOD_GROUP_0_12=LocalFile.PGDynamicdatalists#AddRecordNested
RUN_TEST_CASE_METHOD_GROUP_0_13=LocalFile.PGDynamicdatalists#AddVelocityDisplayTemplate
RUN_TEST_CASE_METHOD_GROUP_0_14=LocalFile.PGDynamicdatalists#ConfigureEditableListPG
RUN_TEST_CASE_METHOD_GROUP_1=1_0 1_1 1_2 1_3 1_4 1_5 1_6 1_7 1_8 1_9 1_10 1_11 1_12 1_13 1_14
RUN_TEST_CASE_METHOD_GROUP_1_0=LocalFile.PGDynamicdatalists#ConfigureSpreadsheetListPG
RUN_TEST_CASE_METHOD_GROUP_1_1=LocalFile.PGDynamicdatalists#DeleteListRecord
RUN_TEST_CASE_METHOD_GROUP_1_2=LocalFile.PGDynamicdatalists#EditFormTemplateLabelAndViewRecord
RUN_TEST_CASE_METHOD_GROUP_1_3=LocalFile.PGDynamicdatalists#EditList
RUN_TEST_CASE_METHOD_GROUP_1_4=LocalFile.PGDynamicdatalists#EditListRecord
RUN_TEST_CASE_METHOD_GROUP_1_5=LocalFile.PGDynamicdatalists#EditListRecordViaRecordView
RUN_TEST_CASE_METHOD_GROUP_1_6=LocalFile.PGDynamicdatalists#SearchDynamicDataListsRecords
RUN_TEST_CASE_METHOD_GROUP_1_7=LocalFile.PGDynamicdatalists#SearchDynamicDataListsRecordsAsUserWithNoPermissions
RUN_TEST_CASE_METHOD_GROUP_1_8=LocalFile.PGDynamicdatalists#SelectList
RUN_TEST_CASE_METHOD_GROUP_1_9=LocalFile.PGDynamicdatalists#SwitchListsViaDDLDisplayAndAssertEditableStillChecked
RUN_TEST_CASE_METHOD_GROUP_1_10=LocalFile.PGDynamicdatalists#ViewBooleanFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_1_11=LocalFile.PGDynamicdatalists#ViewDateFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_1_12=LocalFile.PGDynamicdatalists#ViewDecimalFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_1_13=LocalFile.PGDynamicdatalists#ViewDefaultGuestViewPermissions
RUN_TEST_CASE_METHOD_GROUP_1_14=LocalFile.PGDynamicdatalists#ViewIntegerFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_2=2_0 2_1 2_2 2_3 2_4 2_5 2_6 2_7 2_8 2_9 2_10 2_11 2_12 2_13 2_14
RUN_TEST_CASE_METHOD_GROUP_2_0=LocalFile.PGDynamicdatalists#ViewListRecordAndAssertAnchorLink
RUN_TEST_CASE_METHOD_GROUP_2_1=LocalFile.PGDynamicdatalists#ViewListRecordWithUploadedFreeMarkerDisplayTemplate
RUN_TEST_CASE_METHOD_GROUP_2_2=LocalFile.PGDynamicdatalists#ViewListRecordWithUploadedVelocityDisplayTemplate
RUN_TEST_CASE_METHOD_GROUP_2_3=LocalFile.PGDynamicdatalists#ViewListRecordWithVelocityDisplayTemplate
RUN_TEST_CASE_METHOD_GROUP_2_4=LocalFile.PGDynamicdatalists#ViewNumberFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_2_5=LocalFile.PGDynamicdatalists#ViewPortletWithSpreadsheetViewDisabled
RUN_TEST_CASE_METHOD_GROUP_2_6=LocalFile.PGDynamicdatalists#ViewTextBoxFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_2_7=LocalFile.PGDynamicdatalists#ViewTextFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_2_8=LocalFile.DynamicdatalistsUsecase#AddDataDefinitionWithoutANameAndAssertErrorMessage
RUN_TEST_CASE_METHOD_GROUP_2_9=LocalFile.DynamicdatalistsUsecase#AddListWithoutDataDefinitionAndAssertErrorMessage
RUN_TEST_CASE_METHOD_GROUP_2_10=LocalFile.DynamicdatalistsUsecase#AddListWithXSSWorkflowDefinition
RUN_TEST_CASE_METHOD_GROUP_2_11=LocalFile.DynamicdatalistsUsecase#AddRecord
RUN_TEST_CASE_METHOD_GROUP_2_12=LocalFile.DynamicdatalistsUsecase#AddRecordBlankDateField
RUN_TEST_CASE_METHOD_GROUP_2_13=LocalFile.DynamicdatalistsUsecase#AddRecordWithBlankDocumentsAndMediaField
RUN_TEST_CASE_METHOD_GROUP_2_14=LocalFile.DynamicdatalistsUsecase#AddRecordWithBlankLinkToPageField
RUN_TEST_CASE_METHOD_GROUP_3=3_0 3_1 3_2 3_3 3_4 3_5 3_6 3_7 3_8 3_9 3_10 3_11 3_12 3_13 3_14
RUN_TEST_CASE_METHOD_GROUP_3_0=LocalFile.DynamicdatalistsUsecase#AddRecordWithBlankWebContentField
RUN_TEST_CASE_METHOD_GROUP_3_1=LocalFile.DynamicdatalistsUsecase#AddRecordWithPopulatedWebContentField
RUN_TEST_CASE_METHOD_GROUP_3_2=LocalFile.DynamicdatalistsUsecase#AddRecordWithRepeatableTextField
RUN_TEST_CASE_METHOD_GROUP_3_3=LocalFile.DynamicdatalistsUsecase#AddRepeatableFieldAndAssertOrderInTranslation
RUN_TEST_CASE_METHOD_GROUP_3_4=LocalFile.DynamicdatalistsUsecase#AddRepeatableFieldAsNonAdminUser
RUN_TEST_CASE_METHOD_GROUP_3_5=LocalFile.DynamicdatalistsUsecase#AddSelectFieldWithTranslationAndViewInSpreadsheetView
RUN_TEST_CASE_METHOD_GROUP_3_6=LocalFile.DynamicdatalistsUsecase#AddXSSToHTMLField
RUN_TEST_CASE_METHOD_GROUP_3_7=LocalFile.DynamicdatalistsUsecase#AssertConfigurationMenulist
RUN_TEST_CASE_METHOD_GROUP_3_8=LocalFile.DynamicdatalistsUsecase#AssertDecimalFieldInvalidDataErrorMessage
RUN_TEST_CASE_METHOD_GROUP_3_9=LocalFile.DynamicdatalistsUsecase#AssertFieldAfterNavigatingToManageTemplates
RUN_TEST_CASE_METHOD_GROUP_3_10=LocalFile.DynamicdatalistsUsecase#AssertGuestCannotEditRecord
RUN_TEST_CASE_METHOD_GROUP_3_11=LocalFile.DynamicdatalistsUsecase#AssertIntegerFieldInvalidDataErrorMessage
RUN_TEST_CASE_METHOD_GROUP_3_12=LocalFile.DynamicdatalistsUsecase#AssertNumberFieldInvalidDataErrorMessage
RUN_TEST_CASE_METHOD_GROUP_3_13=LocalFile.DynamicdatalistsUsecase#AssertUserCannotDeleteEntryAfterPermissionRemoved
RUN_TEST_CASE_METHOD_GROUP_3_14=LocalFile.DynamicdatalistsUsecase#AssertUserUpdateRejectedRecord
RUN_TEST_CASE_METHOD_GROUP_4=4_0 4_1 4_2 4_3 4_4 4_5 4_6 4_7 4_8 4_9 4_10 4_11 4_12 4_13 4_14
RUN_TEST_CASE_METHOD_GROUP_4_0=LocalFile.DynamicdatalistsUsecase#CreateSiteAndViewDefaultDataDefinitions
RUN_TEST_CASE_METHOD_GROUP_4_1=LocalFile.DynamicdatalistsUsecase#DeleteStructure
RUN_TEST_CASE_METHOD_GROUP_4_2=LocalFile.DynamicdatalistsUsecase#EditDefaultLanguageAndPublishRecord
RUN_TEST_CASE_METHOD_GROUP_4_3=LocalFile.DynamicdatalistsUsecase#EditListRecordWithNestedFieldViaSpreadsheetView
RUN_TEST_CASE_METHOD_GROUP_4_4=LocalFile.DynamicdatalistsUsecase#FormTemplateUniqueField
RUN_TEST_CASE_METHOD_GROUP_4_5=LocalFile.DynamicdatalistsUsecase#RemoveRepeatableDateField
RUN_TEST_CASE_METHOD_GROUP_4_6=LocalFile.DynamicdatalistsUsecase#RemoveRepeatableFieldAndAssertOrderInTranslation
RUN_TEST_CASE_METHOD_GROUP_4_7=LocalFile.DynamicdatalistsUsecase#SelectLinkToPagePage
RUN_TEST_CASE_METHOD_GROUP_4_8=LocalFile.DynamicdatalistsUsecase#TemplateAddDeletedField
RUN_TEST_CASE_METHOD_GROUP_4_9=LocalFile.DynamicdatalistsUsecase#ViewCannotSaveWithDuplicateFieldNames
RUN_TEST_CASE_METHOD_GROUP_4_10=LocalFile.DynamicdatalistsUsecase#ViewDisplayTemplateClassLinks
RUN_TEST_CASE_METHOD_GROUP_4_11=LocalFile.DynamicdatalistsUsecase#ViewFieldsNestedInDDLRecord
RUN_TEST_CASE_METHOD_GROUP_4_12=LocalFile.DynamicdatalistsUsecase#ViewFormTemplateFieldsAfterBackNavigation
RUN_TEST_CASE_METHOD_GROUP_4_13=LocalFile.DynamicdatalistsUsecase#ViewLinkToPageBreadcrumb
RUN_TEST_CASE_METHOD_GROUP_4_14=LocalFile.DynamicdatalistsUsecase#ViewMultipleDDLRecordsInAssetPublisherAndSortByModifiedDate
RUN_TEST_CASE_METHOD_GROUP_5=5_0 5_1 5_2 5_3 5_4 5_5 5_6 5_7 5_8 5_9 5_10 5_11 5_12 5_13 5_14
RUN_TEST_CASE_METHOD_GROUP_5_0=LocalFile.DynamicdatalistsUsecase#ViewNestedFieldDoesNotDisplayInRecordTable
RUN_TEST_CASE_METHOD_GROUP_5_1=LocalFile.DynamicdatalistsUsecase#ViewNestedFieldEntryWithBlankParentField
RUN_TEST_CASE_METHOD_GROUP_5_2=LocalFile.DynamicdatalistsUsecase#ViewRepeatableNestedFields
RUN_TEST_CASE_METHOD_GROUP_5_3=LocalFile.DynamicdatalistsUsecase#ViewRequiredNestedDocumentsAndMediaField
RUN_TEST_CASE_METHOD_GROUP_5_4=LocalFile.DynamicdatalistsUsecase#ViewUniqueFieldLabels
RUN_TEST_CASE_METHOD_GROUP_5_5=LocalFile.CPDynamicdatalists#AddDisplayTemplateFreeMarker
RUN_TEST_CASE_METHOD_GROUP_5_6=LocalFile.CPDynamicdatalists#AddDisplayTemplateVelocity
RUN_TEST_CASE_METHOD_GROUP_5_7=LocalFile.CPDynamicdatalists#AddFormTemplate
RUN_TEST_CASE_METHOD_GROUP_5_8=LocalFile.CPDynamicdatalists#AddList
RUN_TEST_CASE_METHOD_GROUP_5_9=LocalFile.CPDynamicdatalists#AddListAndRecordWithContactsPredefinedDataDefinition
RUN_TEST_CASE_METHOD_GROUP_5_10=LocalFile.CPDynamicdatalists#AddListAndRecordWithEventsPredefinedDataDefinition
RUN_TEST_CASE_METHOD_GROUP_5_11=LocalFile.CPDynamicdatalists#AddListAndRecordWithInventoryPredefinedDataDefinition
RUN_TEST_CASE_METHOD_GROUP_5_12=LocalFile.CPDynamicdatalists#AddListAndRecordWithIssuesTrackingPredefinedDataDefinition
RUN_TEST_CASE_METHOD_GROUP_5_13=LocalFile.CPDynamicdatalists#AddListAndRecordWithMeetingMinutesPredefinedDataDefinition
RUN_TEST_CASE_METHOD_GROUP_5_14=LocalFile.CPDynamicdatalists#AddListAndRecordWithToDoPredefinedDataDefinition
RUN_TEST_CASE_METHOD_GROUP_6=6_0 6_1 6_2 6_3 6_4 6_5 6_6 6_7 6_8 6_9 6_10 6_11 6_12 6_13 6_14
RUN_TEST_CASE_METHOD_GROUP_6_0=LocalFile.CPDynamicdatalists#AddListRecordWithBooleanField
RUN_TEST_CASE_METHOD_GROUP_6_1=LocalFile.CPDynamicdatalists#AddListRecordWithDateField
RUN_TEST_CASE_METHOD_GROUP_6_2=LocalFile.CPDynamicdatalists#AddListRecordWithDecimalField
RUN_TEST_CASE_METHOD_GROUP_6_3=LocalFile.CPDynamicdatalists#AddListRecordWithDocumentsAndMediaField
RUN_TEST_CASE_METHOD_GROUP_6_4=LocalFile.CPDynamicdatalists#AddListRecordWithGeolocationField
RUN_TEST_CASE_METHOD_GROUP_6_5=LocalFile.CPDynamicdatalists#AddListRecordWithHTMLField
RUN_TEST_CASE_METHOD_GROUP_6_6=LocalFile.CPDynamicdatalists#AddListRecordWithIntegerField
RUN_TEST_CASE_METHOD_GROUP_6_7=LocalFile.CPDynamicdatalists#AddListRecordWithLinkToPageField
RUN_TEST_CASE_METHOD_GROUP_6_8=LocalFile.CPDynamicdatalists#AddListRecordWithNumberField
RUN_TEST_CASE_METHOD_GROUP_6_9=LocalFile.CPDynamicdatalists#AddListRecordWithRadioField
RUN_TEST_CASE_METHOD_GROUP_6_10=LocalFile.CPDynamicdatalists#AddListRecordWithRequiredBooleanField
RUN_TEST_CASE_METHOD_GROUP_6_11=LocalFile.CPDynamicdatalists#AddListRecordWithSelectField
RUN_TEST_CASE_METHOD_GROUP_6_12=LocalFile.CPDynamicdatalists#AddListRecordWithTextBoxField
RUN_TEST_CASE_METHOD_GROUP_6_13=LocalFile.CPDynamicdatalists#AddListRecordWithTextField
RUN_TEST_CASE_METHOD_GROUP_6_14=LocalFile.CPDynamicdatalists#CopyDataDefinition
RUN_TEST_CASE_METHOD_GROUP_7=7_0 7_1 7_2 7_3 7_4 7_5 7_6 7_7 7_8 7_9 7_10 7_11 7_12 7_13 7_14
RUN_TEST_CASE_METHOD_GROUP_7_0=LocalFile.CPDynamicdatalists#CopyDataDefinitionWithCopyDisplayTemplates
RUN_TEST_CASE_METHOD_GROUP_7_1=LocalFile.CPDynamicdatalists#CopyDataDefinitionWithCopyFormTemplates
RUN_TEST_CASE_METHOD_GROUP_7_2=LocalFile.CPDynamicdatalists#CopyDataDefinitionWithCopyFormTemplatesAndCopyDisplayTemplates
RUN_TEST_CASE_METHOD_GROUP_7_3=LocalFile.CPDynamicdatalists#DeleteDataDefinition
RUN_TEST_CASE_METHOD_GROUP_7_4=LocalFile.CPDynamicdatalists#DeleteDisplayTemplateFreeMarker
RUN_TEST_CASE_METHOD_GROUP_7_5=LocalFile.CPDynamicdatalists#DeleteDisplayTemplateVelocity
RUN_TEST_CASE_METHOD_GROUP_7_6=LocalFile.CPDynamicdatalists#DeleteFormTemplate
RUN_TEST_CASE_METHOD_GROUP_7_7=LocalFile.CPDynamicdatalists#DeleteList
RUN_TEST_CASE_METHOD_GROUP_7_8=LocalFile.CPDynamicdatalists#DeleteListRecord
RUN_TEST_CASE_METHOD_GROUP_7_9=LocalFile.CPDynamicdatalists#EditBooleanFieldFieldLabel
RUN_TEST_CASE_METHOD_GROUP_7_10=LocalFile.CPDynamicdatalists#EditBooleanFieldName
RUN_TEST_CASE_METHOD_GROUP_7_11=LocalFile.CPDynamicdatalists#EditBooleanFieldShowLabel
RUN_TEST_CASE_METHOD_GROUP_7_12=LocalFile.CPDynamicdatalists#EditBooleanFieldTip
RUN_TEST_CASE_METHOD_GROUP_7_13=LocalFile.CPDynamicdatalists#EditDataDefinition
RUN_TEST_CASE_METHOD_GROUP_7_14=LocalFile.CPDynamicdatalists#EditDisplayTemplateFreeMarker
RUN_TEST_CASE_METHOD_GROUP_8=8_0 8_1 8_2 8_3 8_4 8_5 8_6 8_7 8_8 8_9 8_10 8_11 8_12 8_13 8_14
RUN_TEST_CASE_METHOD_GROUP_8_0=LocalFile.CPDynamicdatalists#EditDisplayTemplateVelocity
RUN_TEST_CASE_METHOD_GROUP_8_1=LocalFile.CPDynamicdatalists#EditFormTemplate
RUN_TEST_CASE_METHOD_GROUP_8_2=LocalFile.CPDynamicdatalists#EditList
RUN_TEST_CASE_METHOD_GROUP_8_3=LocalFile.CPDynamicdatalists#EditListRecord
RUN_TEST_CASE_METHOD_GROUP_8_4=LocalFile.CPDynamicdatalists#EditListRecordViaRecordView
RUN_TEST_CASE_METHOD_GROUP_8_5=LocalFile.CPDynamicdatalists#EditRadioFieldOptions
RUN_TEST_CASE_METHOD_GROUP_8_6=LocalFile.CPDynamicdatalists#EditRadioFieldOptionsWithUTF8Characters
RUN_TEST_CASE_METHOD_GROUP_8_7=LocalFile.CPDynamicdatalists#EditSelectFieldOptions
RUN_TEST_CASE_METHOD_GROUP_8_8=LocalFile.CPDynamicdatalists#EditSelectFieldOptionsWithUTF8Characters
RUN_TEST_CASE_METHOD_GROUP_8_9=LocalFile.CPDynamicdatalists#ImportLAR
RUN_TEST_CASE_METHOD_GROUP_8_10=LocalFile.CPDynamicdatalists#ViewBooleanFieldPredefinedValue
RUN_TEST_CASE_METHOD_GROUP_8_11=LocalFile.CPDynamicdatalists#ViewCannotAddNonAlphanumericCharactersToFieldName
RUN_TEST_CASE_METHOD_GROUP_8_12=LocalFile.CPDynamicdatalists#ViewFormTemplateFieldReadOnlyWithEditMode
RUN_TEST_CASE_METHOD_GROUP_8_13=LocalFile.CPDynamicdatalists#ViewFormTemplateFields
RUN_TEST_CASE_METHOD_GROUP_8_14=LocalFile.CPDynamicdatalists#ViewFormTemplateFieldsAfterSaveAndContinue
RUN_TEST_CASE_METHOD_GROUP_9=9_0 9_1 9_2 9_3 9_4 9_5 9_6 9_7
RUN_TEST_CASE_METHOD_GROUP_9_0=LocalFile.CPDynamicdatalists#ViewListRecordAndAssertAnchorLink
RUN_TEST_CASE_METHOD_GROUP_9_1=LocalFile.CPDynamicdatalists#ViewNoDuplicatesInOriginalAfterCopy
RUN_TEST_CASE_METHOD_GROUP_9_2=LocalFile.CPDynamicdatalists#ViewRecordInfoSidebar
RUN_TEST_CASE_METHOD_GROUP_9_3=LocalFile.WorkflowDDL#EditDDLRecordViaMyWorkflowTasks
RUN_TEST_CASE_METHOD_GROUP_9_4=LocalFile.WorkflowDDL#RejectDynamicdatalistCP
RUN_TEST_CASE_METHOD_GROUP_9_5=LocalFile.WorkflowForms#SubmitPublishedFormWithTextField
RUN_TEST_CASE_METHOD_GROUP_9_6=LocalFile.WorkflowForms#ViewDateAssetDetails
RUN_TEST_CASE_METHOD_GROUP_9_7=LocalFile.WorkflowForms#ViewEntryWithConditionalVisibilityFromSelectAndRadio
RUN_TEST_CASE_METHOD_GROUPS=0 1 2 3 4 5 6 7 8 9
```

**Comment by alexcandidos** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
Hi guys, I'm only tagging you here because I did not face this kind of issue when forwarding to BChan. @kenjiheigel @yichenroy

I'm calling `ci:forward` again.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by yichenroy** [comment]
@alexcandidos we've been getting reports on forwarding failures like you've seen here.
We'll investigate and resolve the issue in this ticket: https://issues.liferay.com/browse/LRCI-1761

**Pull request closed without merging**
