### PR TITLE
LRQA-79009 - New Automated tests for Basic exercises

### PR DESCRIPTION
**Pull request by henriquelimadotcom**
**Ticket:**
https://issues.liferay.com/browse/LRQA-79009

**Test Cases:**
MyDmTest#CanDownloadDM
MyDmTest#CanEditDM
MyDmTest#CanDeleteDM
MyDmTest#CanCreateDM

MyBlogTests#CanCreateBlog
MyBlogTests#CanDeleteBlog
MyBlogTests#CanEditBlog
MyBlogTests#CanSearchBlogs

MyTestFile#FormsTranslate
MyTestFile#SetScreenSizeAndValidateValues
MyTestFile#ValidateConfigurationStringAtControlPanel

### CODE REVIEW

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
@liferay-continuous-integration

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by WillamesVital** [comment]
I will review this Pull Request

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Pull request closed without merging**
