### PR TITLE
LRAC-8120 Adding ViewAllFormsShownInAssetList Testcase

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Review by ViniLopes20 — COMMENTED** [review]
LGTM!

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @91nilo , Thanks for working on it!

The code looks good to me!

**Review by alexcandidos — APPROVED** [review]
Hi @91nilo , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
