### PR TITLE
LRQA 54500 | Master

### PR DESCRIPTION
**Pull request by tainguyen100**
https://issues.liferay.com/browse/LRQA-54500

### CODE REVIEW

**Comment by tainguyen100** [comment]
SF Passed: https://github.com/tainguyen100/liferay-portal/pull/6

**Comment by tainguyen100** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Just started reviewing :)

**Comment by alexcandidos** [comment]
Hey @tainguyen100 , thanks for your contribution! I've downloaded and added made some changes into your code, forwarded to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/86028

**Pull request closed without merging**
