### PR TITLE
master-qa-126419-2

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-126419

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
Thanks @melodywu !

Pushed to liferay-qa: https://github.com/liferay-qa/liferay-portal/pull/234

**Pull request closed without merging**
