### PR TITLE
AC Stub Test - LRAC-8466 | master 

### PR DESCRIPTION
**Pull request by LucasAcacio**
https://issues.liferay.com/browse/LRAC-8495

### CODE REVIEW

**Comment by LucasAcacio** [comment]
ci:test:sf

**Review by pedro-michel — COMMENTED** [review]
Priority Reviewed

**Comment by alexcandidos** [comment]
Hi @LucasAcacio  , thanks for working on it!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
