### PR TITLE
AC Stub Test - LRAC-8670 | master

### PR DESCRIPTION
**Pull request by rafaellajordao**
https://issues.liferay.com/browse/LRAC-8670

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Review by pedro-michel — COMMENTED** [review]
Priority Reviewed

**Comment by alexcandidos** [comment]
Hi @rafaellajordao , thanks for working on it!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
