### PR TITLE
LPS-103895 Avoids NPE

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:test:app-builder

**Comment by alexcandidos** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Pull request closed without merging**
