### PR TITLE
LRQA-54502 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-54502
AppBuilder#ReuseExistingFormViewFields

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hey @nkkwon , could you please rebase your code and send it again, so we can only see your code. Thanks!

**Comment by nkkwon** [comment]
Hey @alexcandidos I rebased this branch and it's up to date

**Comment by alexcandidos** [comment]
Hey @nkkwon , could you please take a look again?

**Pull request closed without merging**
