### PR TITLE
LRAC-8536 Change Blog and DM creation to use API

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-8536

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
This is awesome @ViniLopes20 !!! 🎉 🚀

**Comment by alexcandidos** [comment]
ci:forward

**Comment by joshitagaki** [comment]
This is great! Thanks @ViniLopes20

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
