### PR TITLE
AC Automated Test LRAC-8429 | master

### PR DESCRIPTION
**Pull request by LucasAcacio**
https://issues.liferay.com/browse/LRAC-8429

### CODE REVIEW

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
Hi @LucasAcacio , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
Conflicts fixed and sent via https://github.com/liferay-qa/liferay-portal/pull/709

fyi @LucasAcacio

**Comment by alexcandidos** [comment]
hey @LucasAcacio , I fixed the conflicts and rebased but it is still getting errors on https://github.com/liferay-qa/liferay-portal/pull/709, https://github.com/liferay-qa/liferay-portal/pull/710 and https://github.com/liferay-qa/liferay-portal/pull/711, could you please monitor take a look at your branch LRAC-8429 and resend?

Thanks!

**Pull request closed without merging**
