### PR TITLE
LRQA-57187 Updating Translation#ADD selector to be more generic

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
fyi @cvanut, I'm updating this selector to be more generic and cover both DDL and Form cases. Your changes here https://github.com/liferay/liferay-portal/commit/b053aa43ef0ca6aee448963b1595c9feef50cb33 made these 6 DDL scripts start to fail:

DynamicdatalistsUsecase#AssertGuestCannotEditRecord
DDMStructureWithNestedTextField#ViewFieldTranslations
DynamicdatalistsUsecase#AddRepeatableFieldAndAssertOrderInTran...
DynamicdatalistsUsecase#RemoveRepeatableFieldAndAssertOrderInT...
DynamicdatalistsUsecase#EditDefaultLanguageAndPublishRecord
DynamicdatalistsUsecase#AddSelectFieldWithTranslationAndViewIn...

Please, before submitting a change in a macro/path file, make sure the other tests that are using this code are still ok.

I've checked Forms#AddElementSetsWithTranslation test case and it is okay with my change. 
Thanks!

**Comment by alexcandidos** [comment]
ci:forward

**Comment by cvanut** [comment]
Hey @alexcandidos . Thanks for the update.

**Pull request closed without merging**
