### PR TITLE
master-lps-126424

### PR DESCRIPTION
**Pull request by felix3508**

### CODE REVIEW

**Comment by felix3508** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @felix3508 , thanks! It looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:stop

**Comment by alexcandidos** [comment]
Pushed to liferay-qa: https://github.com/liferay-qa/liferay-portal/pull/60

**Pull request closed without merging**
