### PR TITLE
LPS-104454 | master

### PR DESCRIPTION
**Pull request by brookedalton**
Hey @alexcandidos, let me know if you want me to make any other changes, thanks! :)

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:app-builder

**Comment by alexcandidos** [comment]
Thanks for the adjustments and for the new test case @brookedalton !!

**Comment by alexcandidos** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/81165. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alexcandidos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alexcandidos** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81166. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
