### PR TITLE
LPS-113847 viewMode should be true when using the form renderer

### PR DESCRIPTION
**Pull request by brunofarache**
@alexcandidos @cvanut please test this fix on app builder and forms to see if there was any side effect.

cc @alinedoleron

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:test:forms

**Comment by brunofarache** [comment]
ci:test:app-builder

**Comment by brunofarache** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@alexcandidos @brunofarache if you're satisfied with the test results, please forward this critical fix directly to Brian Chan (and just `ci:reopen` the pull when it autocloses). It's not worth it in this case to wait for tests to pass.

**Comment by alexcandidos** [comment]
Hi @jpince , thank you for following up! I'll download this PR to check manually. I've checked the results of app-builder routine here and it is equal to CI. I've triggered the relevant again only due to the semantic versioning issue that happened. I don't know if it is related to Bruno's changes since I saw that it also happened on app-builder routine on CI this night.

cc: @brunofarache

**Comment by brunofarache** [comment]
@alexcandidos my change is not a breaking change, that semantic error should be something else.

**Comment by alexcandidos** [comment]
I agree with you @brunofarache , that's what I said ! :)

**Comment by alexcandidos** [comment]
Just started reviewing :)

**Comment by alexcandidos** [comment]
Test Result: PASSED Manual Testing following the steps in the description.
Actual Result: Options related to pages are not shown when adding an entry of an App.

**Comment by alexcandidos** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/88892.

**Pull request closed without merging**
