### PR TITLE
LPS-126829

### PR DESCRIPTION
**Pull request by brunoquei2105**

### CODE REVIEW

**Comment by alexcandidos** [comment]
Hey @brunoquei2105 , you forgot the LPS in one of the commit messages, I fix it for you. Please, review it before pushing next time. :)

Pushed to liferay-qa: https://github.com/liferay-qa/liferay-portal/pull/162
Please, follow the review.

**Comment by brunoquei2105** [comment]
Sorry Alex, my fault. Next i will be careful

**Comment by brunoquei2105** [comment]
Sorry @alexcandidos , my fault. Next time i will be careful.

**Comment by alexcandidos** [comment]
Hey @brunoquei2105 , we just noticed that you implemented this test in Web Content scope (structures) . It should be implemented in Documents and Media (Document type) scope. 

cc: @emanuelfisilva

**Pull request closed without merging**
