### PR TITLE
AC Stub Test - LRAC-8418, LRAC-8422, LRAC-8425, LRAC-8427, LRAC-8430, LRAC-8432, LRAC-8434 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-8418
https://issues.liferay.com/browse/LRAC-8422
https://issues.liferay.com/browse/LRAC-8425
https://issues.liferay.com/browse/LRAC-8427
https://issues.liferay.com/browse/LRAC-8430
https://issues.liferay.com/browse/LRAC-8432
https://issues.liferay.com/browse/LRAC-8434

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
