### PR TITLE
AC Stub Test - LRAC-8689, LRAC-8701 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-8689
https://issues.liferay.com/browse/LRAC-8701

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Review by pedro-michel — COMMENTED** [review]
Priority Reviewed

**Comment by alexcandidos** [comment]
Hi @91nilo @pedro-michel , thanks for working on it!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
