### PR TITLE
LRQA-79086 | Automation of MyTestFiles exercises

### PR DESCRIPTION
**Pull request by davisaints**
* https://issues.liferay.com/browse/LRQA-79086

* Test Cases:

1. MyTestFile#CanCreateFormSubmitFormValidateLanguage 
2. MyTestFile#SetScreenSizeAndValidateValues
3. MyTestFile#ValidateConfigurationStringAtControlPanel

### CODE REVIEW

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:test:sf

**Comment by davisaints** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
Muito bom, @davisaints  Obrigado.

**Pull request closed without merging**
