### PR TITLE
AC Stub Test - LRAC-8397, LRAC-8404, LRAC-8413, LRAC-8416, LRAC-8420 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-8397
https://issues.liferay.com/browse/LRAC-8404
https://issues.liferay.com/browse/LRAC-8413
https://issues.liferay.com/browse/LRAC-8416
https://issues.liferay.com/browse/LRAC-8420

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @91nilo , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
