### PR TITLE
master-qa-126419-1

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-126419

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
Hey @melodywu , I'm closing this PR just to clean-up my queue. Please, feel free to open a new PR when you finish the implementation adding the remaining steps as we were discussing in the ticket https://issues.liferay.com/browse/LPS-126419. 

Thank you!

**Pull request closed without merging**
