### PR TITLE
LRQA-54496 - Automate LPS-96002 - As an App Adm, I want to publish my app in the product menu

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:app-builder

**Comment by alexcandidos** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/84499. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alexcandidos** [comment]
Thanks for the script @rodrigocunhaa !!

**Pull request closed without merging**
