### PR TITLE
master-qa-126419

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-126419

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
Hi @melodywu , I believe you need to add translations for all the fields added to the structure (for example, translating the field labels) then, create a web content based on the created structure and then switch language there and make sure the field labels are properly translated according to the language previously set in the structure.

**Comment by melodywu** [comment]
Hi @alexcandidos，Thanks for you and Emanuel Silva 's help. I will rewrite the testcase according to the steps you suggested. I will 
reference the steps on [spira](https://liferay.spiraservice.net/16/TestCase/List/7296.aspx) for other testcases too. Thanks a lot.

**Comment by alexcandidos** [comment]
Thanks @melodywu ! I'm closing this PR for now to clean up my PR queue.

**Pull request closed without merging**
