### PR TITLE
AC Automated Test - LRAC-8149 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-8149

### CODE REVIEW

**Comment by christianstokes** [comment]
See comment on here: https://github.com/alexcandidos/liferay-portal/pull/495#issuecomment-888468133

Want to make sure we're testing the right thing.

**Comment by alexcandidos** [comment]
Hi @christianstokes , I just clarified this on https://github.com/alexcandidos/liferay-portal/pull/495#issuecomment-890263740.

Please check @AfonsoHSantos , and update the test here too. ;)

Aside that, the code looks good to me!

Thanks for working on it! :)

**Comment by AfonsoHSantos** [comment]
Hi @alexcandidos, I made the changes you asked for!

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
