### PR TITLE
LPS-101525 Fixes actions when translating

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alexcandidos** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/1099. [See changes here.](https://github.com/alexcandidos/liferay-portal/compare/ad0c4b4d5d61~3...ad0c4b4d5d61) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
