### PR TITLE
AC Stub Test - LRAC-8655, LRAC-8672, LRAC-8674, LRAC-8680 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-8655
https://issues.liferay.com/browse/LRAC-8672
https://issues.liferay.com/browse/LRAC-8674
https://issues.liferay.com/browse/LRAC-8680

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Review by pedro-michel — COMMENTED** [review]
Priority Reviewed

**Comment by alexcandidos** [comment]
Hi @91nilo , thanks for working on it!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
