### PR TITLE
AC Stub Test - LRAC-8354 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-8354

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , please do a rebase-interactive and update one of your commit messages, it is failing on source format because the commit is not starting with the ticket ID LRAC-XXXX.

Thanks!

**Comment by alexcandidos** [comment]
Also, you are using the wrong ticket id to commit, it should be LRAC-8354 instead of LRAC-8349. Please, update it, thanks!

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
hi @alexcandidos, i made the changes!

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
