### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test

**Comment by alexcandidos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
Pull request submitted to https://github.com/alexcandidos/liferay-portal/pull/24. [See changes here.](https://github.com/alexcandidos/liferay-portal/compare/012d44b5d0b9~1...012d44b5d0b9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
