### PR TITLE
AC Stub Test - LRAC-8376, LRAC-8393, LRAC-8392, LRAC-8390, LRAC-8389 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-8376
https://issues.liferay.com/browse/LRAC-8393
https://issues.liferay.com/browse/LRAC-8392
https://issues.liferay.com/browse/LRAC-8390
https://issues.liferay.com/browse/LRAC-8389

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
