### PR TITLE
LRAC-8315

### PR DESCRIPTION
**Pull request by rafaellajordao**

### CODE REVIEW

**Comment by ViniLopes20** [comment]
Hi, @rafaellajordao. Commits always starting with LRAC-XXXX (XXX -> Your branch number).

because it won't give an error when calling `ci:forward`

**Comment by alexcandidos** [comment]
Hi @rafaellajordao , please see my comment here https://github.com/alexcandidos/liferay-portal/pull/510#issuecomment-893875039

**Comment by rafaellajordao** [comment]
fixed! @alexcandidos and @ViniLopes20 !

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @rafaellajordao , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
